# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
      ##
    - name: Compilar Main com o Java
      run: javac -cp src src/Main.java

    - name: Compilar Classe com o Java
      run: javac -cp src src/CalculadoraDoisTeste.java
      
    - name: Executando o Java
      run: |
            cd src
            java -cp . CalculadoraDoisTeste
    - name: Obtendo a versão atual 
      id: get_version 
      run: echo ::set-output name=version::$(cat version.txt) 
      
    - name: Incrementando a versão 
      id: increment_version 
      run: echo ::set-output name=version::$((${{ steps.get_version.outputs.version }} + 1)) 
      
    - uses: mr-smithers-excellent/docker-build-push@v6 
      name: Build & push Docker image 
      with: 
        image: isabelaiff/calculadoradois
        tags: latest, ${{ steps.increment_version.outputs.version }} 
        registry: docker.io 
        dockerfile: dockerfile 
        username: ${{ secrets.DOCKER_USERNAME }} 
        password: ${{ secrets.DOCKER_PASSWORD }}

